theater = [{
        'id': 1,
        'img': '/eventImg/befikrn.jpg',
        'name': "Befikr",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "No Limit",
        'description': "Theatre takes you into a world where your imagination is stimulated, your judgement is unimpaired and thus your enjoyment heightened. - Naseeruddin Shah <br> For those who have drama embedded in their system,  a stage is an elixir to life.  For those who have sensations pulsating within them,  we have a spell to cast upon you.  Blow the Theatrical fire and show your play. Gather your twigs,  come our way; we'll provide a stage for you to slay. All teams would be required to submit video entries for the prelims. <br> Top 6 teams would be selected for the final (on-spot) round based on preliminary round, and get to perform at Odyssey ‘20. <br> The winning team takes home grand cash prizes, along with a major sense of accomplishment and pride.",
        'rules': [
            "Time limit: 40 min (including setup time) (for on-spot round)", 
            "For the preliminary round, the time limit of the video entries submitted  should not exceed 20 mins.",
            "The play could be presented in either Hindi or English or both.",
            "Teams need to enact a play keeping in mind the above mentioned criteria without any theme.",
            "Judges have the right to stop your performance in between.",
            "The decision of the judges will be final and binding. Showing dissent at judges’ decision in any way will not be acceptable.",
            "One person can be a member of only one team. Heavy penalty shall be imposed on both teams if this is violated.",
            "Crews consisting of participants from mixed colleges are allowed.",
            "Usage of props is allowed. These have to be brought by the teams themselves but the organizers hold the discretion of allowing it on stage.",
            "In case the team wishes to use music, pre-recorded music should be brought in a pen drive in .mp3 format only and must be mailed to us at least 2 hours prior to the event.",
            "Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has possibility of tampering/damaging the stage is STRICTLY not allowed.",
            "The seats are supposed to be used for the seating of audiences ONLY and under no circumstances, be used for any other purpose like leaving some space for the performance.",
            "Obscenity of any kind is not allowed and will lead to immediate disqualification.",
            "Violation of any of the above rules, will lead to heavy penalties."
        ],
        'regLink': "http://bit.ly/befikr20",
    }, {
        'id': 2,
        'img': '/eventImg/hasratein.jpg',
        'name': "Hasratein",
        'date': "17 & 18th Jan",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "Maximum of 25",
        'description': "'Sunna hai nukkad walle Hasratein mai aana nhi bhulte!'Hasratein, the Flagship event of Odyssey is back to provide you with a platform to showcase your acting skills and raise your voice for a good cause <br>.While there are many ways of ‘spreading the word’, street plays are a grassroot manifestation that is not only educational, but have the power of word of mouth. <br>So, mark the dates on your calendar and gear up to present yourself in one of the most happening events of Odyssey '20",
        'rules': [
            "‌The play should be original. Plagiarism will lead to disqualification of the teams. ", 
            "Use of fire/water/smoke machines (or anywhere in its vicinity) is strictly prohibited. Use of any sort of hazardous element/prop is strictly prohibited. ",
            "‌Time Limit - 30 minutes. Warning bell will be rung after 25 minutes. The time limit should not exceed 30 minutes. Exceeding the time limit would lead to deduction of marks.",
            "Max No. of Participants per group: 25",
            "Any kind of obscenity will lead to immediate disqualification.",
            "Judges’ collective decision will be final and binding."
        ],
        'regLink': "http://bit.ly/hasratein20",
    }, {
        'id': 3,
        'img': '/eventImg/unscripted_fbcover.jpg',
        'name': "Unscripted",
        'date': "18th Jan",
        'time': "10:00 AM - 2:00 PM",
        'venue': "C21",
        'prize': "TBA",
        'team': "1 Member",
        'description': "When something goes wrong in your life, just yell 'Plot twist' and move on! Improv, a form of live theatre in which the plot, characters and dialogue of a game, scene or story are made up in the moment, is one of the most exciting forms of theatre.  <br>It provides a platform for you to explore your ability to respond to surprises.",
        'rules': [
            "The event will comprise of three rounds where the teams will have to perform some amusing tasks."
        ],
        'regLink': "http://bit.ly/unscript3d",
    }, 
]
literary = [{
        'id': 1,
        'img': '/eventImg/Literary Quiz_FB.jpg',
        'name': "Literary Quiz",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "2 Members",
        'description': "So you call yourself a nerd? Have more fandom merch than normal apparel? Do you relate more to sonnets than you ever did to rap songs? Does your head contain better quotes than Goodreads could ever offer? A million theme songs stuck in your head the way you only wish inorganic chemistry once had? But do you have it in you to compete? Welcome to the Lit Quiz, where we promise to put to test all that literary knowledge you’ve acquired over the years at every question, connect and pounce. May the best bibliophile win!",
        'rules': [
            "Number of Rounds: 3", 
            "Round 1: A written quiz which will be a literary pot pourri. ",
            "Marking Criteria- Differential marking",
            "Top 8-10 teams will be shortlisted and would participate in Round 2.",
            "Round 2: Two rounds of 10 questions each with infinite bounce and pounce. The questions would span everything from Classical to Modern literary works, history of literature, mind-boggling rebuses and adages. A pictionary/dumb charades round would follow. ",
            "Top 5-7 teams from this round would participate in Round 3.",
            "Round 3: Each round will be themed and be a buzzer round.  ",
            "In case of tie, rapid fire round will be held.",
            "Decision of quizmaster in any case will be final and binding."
        ],
        'regLink': "http://bit.ly/TheLitQuiz",
    }, {
        'id': 2,
        'img': '/eventImg/turnquote_fb_cover.jpg',
        'name': "Turn Quote",
        'date': "17 & 18th Jan",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'description': "Turn Quote is a debating competition which provide a platform to debaters from debating societies of renowned colleges to express their views and opinions on different topics . <br>It will be a two day event. <br>Turn Quote 2020 welcomes you!<br> Winners will receive amazing prizes! All participants will receive certificates and amazing goodies! ",
        'rules': [
            "Every team will get 10 mins to speak with a negotiable time limit of 1 min.", 
            "The 10 mins are distributed as - First five mins will be for introduction of your topic. Then your oppositon team will do the same.",
            "Next 3 mins(Question Round) - In this round you can question other team and put forward more points in favour of your topic.",
            "Next 2 mins(Defense round) - In this round you have to give answers to the questions asked by other team in the questioning round."
        ],
        'regLink': "http://bit.ly/Turnquote",
    }, {
        'id': 3,
        'img': '/eventImg/Punchline-01.jpg',
        'name': "Punchline",
        'date': "TBA",
        'time': "1 Member",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "𝙎𝙖𝙗𝙨𝙚 𝘼𝙘𝙝𝙝𝙖 𝘾𝙤𝙢𝙞𝙘-𝙆𝙖𝙪𝙣? 𝐈𝐭 𝐭𝐚𝐤𝐞𝐬 𝐚 𝐟𝐞𝐰 𝐝𝐫𝐨𝐩𝐬 𝐨𝐟 𝐡𝐮𝐦𝐨𝐫 𝐭𝐨 𝐚𝐝𝐝 𝐥𝐢𝐟𝐞 𝐭𝐨 𝐚 𝐛𝐥𝐚𝐧𝐝 𝐚𝐧𝐝 𝐭𝐢𝐫𝐞𝐬𝐨𝐦𝐞 𝐝𝐚𝐲. 𝐁𝐮𝐭 𝐜𝐨𝐦𝐞𝐝𝐲 𝐢𝐬 𝐦𝐨𝐫𝐞 𝐭𝐡𝐚𝐧 𝐣𝐮𝐬𝐭 𝐡𝐮𝐦𝐨𝐫. 𝐈𝐭 𝐢𝐬 𝐚𝐛𝐨𝐮𝐭 𝐜𝐨𝐧𝐟𝐢𝐝𝐞𝐧𝐜𝐞, 𝐰𝐢𝐭, 𝐚𝐧𝐝 𝐮𝐧𝐝𝐞𝐫𝐬𝐭𝐚𝐧𝐝𝐢𝐧𝐠 𝐨𝐟 𝐭𝐡𝐞 𝐚𝐮𝐝𝐢𝐞𝐧𝐜𝐞. 𝐎𝐝𝐲𝐬𝐬𝐞𝐲'𝟐𝟎 𝐩𝐫𝐞𝐬𝐞𝐧𝐭𝐬 𝐏𝐮𝐧𝐜𝐡𝐥𝐢𝐧𝐞, 𝐰𝐡𝐞𝐫𝐞 𝐭𝐚𝐥𝐞𝐧𝐭𝐞𝐝 𝐜𝐨𝐦𝐞𝐝𝐢𝐚𝐧𝐬 𝐮𝐩 𝐭𝐡𝐞 𝐠𝐚𝐦𝐞 𝐨𝐟 𝐡𝐮𝐦𝐨𝐫, 𝐚𝐬 𝐭𝐡𝐞𝐲 𝐜𝐨𝐦𝐩𝐞𝐭𝐞 𝐚𝐭 𝐭𝐡𝐢𝐬 𝐩𝐥𝐚𝐭𝐟𝐨𝐫𝐦. 𝐏.𝐒. - 𝐈𝐟 𝐲𝐨𝐮 𝐠𝐞𝐭 𝐬𝐡𝐨𝐫𝐭𝐥𝐢𝐬𝐭𝐞𝐝, 𝐲𝐨𝐮'𝐥𝐥 𝐡𝐚𝐯𝐞 𝐭𝐨 𝐜𝐨𝐦𝐞 𝐭𝐨 𝐈𝐈𝐈𝐓 𝐃𝐞𝐥𝐡𝐢 𝐨𝐧 𝟏𝟕𝐭𝐡 𝐉𝐚𝐧𝐮𝐚𝐫𝐲'𝟐𝟎 𝐟𝐨𝐫 𝐭𝐡𝐞 𝐅𝐢𝐧𝐚𝐥 𝐑𝐨𝐮𝐧𝐝. 𝐏𝐥𝐞𝐚𝐬𝐞 𝐛𝐞 𝐩𝐫𝐞𝐩𝐚𝐫𝐞𝐝 𝐰𝐢𝐭𝐡 𝐚 𝟕-𝟏𝟎 𝐦𝐢𝐧𝐮𝐭𝐞 𝐒𝐭𝐚𝐧𝐝-𝐔𝐩 𝐟𝐨𝐫 𝐭𝐡𝐞 𝐟𝐢𝐧𝐚𝐥 𝐫𝐨𝐮𝐧𝐝. 𝐒𝐨 𝐠𝐞𝐭 𝐫𝐞𝐚𝐝𝐲 𝐭𝐨 𝐭𝐢𝐜𝐤𝐥𝐞 𝐨𝐮𝐫 𝐟𝐮𝐧𝐧𝐲 𝐛𝐨𝐧𝐞 𝐚𝐭 𝐭𝐡𝐞 𝐠𝐫𝐞𝐚𝐭𝐞𝐬𝐭 𝐬𝐭𝐚𝐧𝐝-𝐮𝐩 𝐜𝐨𝐦𝐞𝐝𝐲 𝐜𝐨𝐦𝐩𝐞𝐭𝐢𝐭𝐢𝐨𝐧. 𝐂𝐨𝐦𝐞 𝐭𝐨 𝐏𝐮𝐧𝐜𝐡𝐥𝐢𝐧𝐞 𝐭𝐨 𝐬𝐡𝐨𝐰 𝐨𝐟𝐟 𝐲𝐨𝐮𝐫 𝐬𝐤𝐢𝐥𝐥𝐬 𝐚𝐧𝐝 𝐞𝐚𝐫𝐧 𝐟𝐚𝐧𝐭𝐚𝐬𝐭𝐢𝐜 𝐩𝐫𝐢𝐳𝐞𝐬!", 
        'rules': [
            " It is a solo competition ", 
            "A time limit of the act is 10 minutes, with a penalty for going beyond it ",
            "Performance can be in Hindi, English or both ",
            "Carrying chits or looking into mobile phones will result in a penalty (however, you can come up with your own creative ideas ) ",
            "At max one prop is allowed ",
            "Content shouldn’t explicitly hurt the sentiments of any person/community ",
            "No explicit vulgarity or obscene content. Subtlety, however, is welcomed ",
            "The judges’ decision would be binding and final ",
            "It would be ideal if you remember the perspectives of others and take mind not to irritate/hurt suppositions purposefully/unexpectedly.",
            "Marking will be based on :  1. Quality of content   2. Presentation and timing  3. Audience response and applause  4. The overall impact of the act"
        ],
        'regLink': "http://bit.ly/PunchlineOdyssey",
    }, {
        'id': 4,
        'img': '/eventImg/unmute fb-cover.jpg',
        'name': "Unmute",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'description': "Event Structure: The event is split into two parts :- a slam poetry competition and an open mic. Three guest performers have been invited for this event who will perform one after the other after the first half of the slam poetry competition is over. ",
        'rules': [
            "Time limit : 5 minutes", 
            "There is no specific theme that needs to be followed.",
            "Strict plagiarism policy. Only original content will be allowed.",
            "On the spot registrations allowed for the open mic only if the cap on the number hasn’t been reached. (There will be an announcement regarding that a week prior to the fest)",
            "Organizers’ decision is final and binding."
        ],
        'regLink': "http://bit.ly/unmute_odyssey",
    }, {
        'id': 5,
        'img': '/eventImg/16wtg_cover.jpg',
        'name': "16 Words To Go",
        'date': "TBA",
        'time': "TBA",
        'venue': "Online",
        'prize': "TBA",
        'team': "1 Member",
        'description': "Want to get your creative side out but you don't have much time???? Well then 16 words to go is the platform you were missing....16 words to go is an online event , which requires you to bring out literary talent and write only 16 words on the theme provided. So get ready to get on an exciting literary journey. Follow us on Instagram @16wtg for further updates.",
        'rules': [
            "No. of words should not exceed 16.", 
            "Should follow anyone of the themes provided.",
            "Originality. All the entries will be checked for plagiarism.",
            "Can be in English or Hindi. You can write a poem , story or anything else.",
            "There will be a total of two rounds, both online.",
            "Following us on Instagram is very important, no. of likes your post gets can also be a judgement criteria!!!!"
        ],
        'regLink': "http://bit.ly/16WordsToGo",
    }, {
        'id': 6,
        'img': '/eventImg/punwars.jpg',
        'name': "Pun Wars",
        'date': "17 & 18th Jan",
        'time': "TBA",
        'venue': "Online",
        'prize': "TBA",
        'team': "1 Member",
        'description': "To pun or not to pun. That is the intention. This event is for all the guys and girls in the group who just can't stop themselves from cracking a puntastic joke in the conversation. ",
        'rules': [
            "There will be themes given. ", 
            " All the punsons need to comment one or more pun(s) relevant to the theme. ",
            "Comments with the most likes will win exciting prizes!"
        ],
        'regLink': "https://www.facebook.com/events/708093302934816/",
    }, {
        'id': 7,
        'img': '/eventImg/vvv_cover.jpg',
        'name': "Verses vs Verses",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "‘Verses vs Verses’ is a bilingual IMPROV POETRY event, thinking out of the box, off the track, you are not gonna come prepared with your works, but this is a public oral recitation and performance of poetry or a verse written on the spot! This event will give writers a unique opportunity to share their work, receive immediate feedback and interact with other artistic people. <br> ROUND 1 - Improv poetry- rhyming or free verse(BONUS points if you doodle something!) With random chit- picking process, 4 people will be called up, from a set of prompts created by the organising team, a prompt will be announced, 5 minutes ( in totality 5 and not 5*4)  would be given to all to think and write about 2-4 lines, in the order of chits being picked, after 5 minutes, the participants will be called one by one, and asked to read or recite their content out. <br> After this, A different set of 4 people will be called, and the next prompt will be announced, 5 minutes would be given to all to think and write about 2-4 lines, This would go on till all participants are covered. <br> If it is not you in the set of 4, i.e. not your turn to write;  breathe, relax and listen to your peers! <br> Top 10 participants(judged on the basis of recited work, content, delivery, presence of mind) reach the next round. <br> ROUND 2-  Visual improv <br> 15 prompts would be displayed on the screen. On the basis of spontaenity, a person can chose his prompt.( In case of clash, whoever calls first get priority) <br> 10 minutes would be given to the participants(in totality 10 and not 10*10). They are expected to come up with a beautiful poem or prose.",
        'rules': [
            "No use of technology is allowed or encouraged throughout the event."
        ],
        'regLink': "http://bit.ly/versesvsverses",
    }, {
        'id': 8,
        'img': '/eventImg/MemeWars2-01-01.jpg',
        'name': "Meme Wars",
        'date': "Round 1 (Date: 25th Dec to 12th Jan) & Round 2 (Date: 17th Dec)",
        'time': "TBA",
        'venue': "Round 1 (Online) & Round 2 (B.Tech Labs)",
        'prize': "TBA",
        'team': "Maximum of 2 Members",
        'description': "Are you memed up enough to survive the ultimate battle? <br> Odyssey'20 brings to you the Meme Wars! <br> The event would be conducted in two rounds - offline and online. You would be given a few prompts to make a meme on. You can choose any three of them and submit a single entry per prompt. You would be free to use any meme template you like (hint: something unique is bound to fetch you bonus marks though). Your entries are going to be crowdsourced, so plagiarism is a strict no-no. <br> Round 1: What? - online round When? - 5 to 15 January You would be given a few prompts to make a meme on. You can choose any three of them and submit a single entry per prompt. You would be free to use any meme template you like (hint: something unique is bound to fetch you bonus marks though). Your entries are going to be crowdsourced, so plagiarism is a strict no-no. The prompts and definite rules for the round would be revealed eventually. Shortlisted people from round 1 will participate in round 2. <br> Round 2: What?: - offline round, When?: - 17 January, A surprise round, but we can spare a hint - Hunt them memes!",
        'rules': [
            "Cash prizes for winners and for the most liked entry/ies of round 1 and 2!"
        ],
        'regLink': "https://www.facebook.com/events/1371339029692624/",
    }, {
        'id': 9,
        'img': '/eventImg/haiku.jpg',
        'name': "",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Your description para",
        'regLink': "http://bit.ly/OdysseyHaiku",
    }, {
        'id': 10,
        'img': '/eventImg/Content Writing_FB.jpg',
        'name': "Content Writing",
        'date': "TBA",
        'time': "TBA",
        'venue': "Online",
        'prize': "TBA",
        'team': "TBA",
        'description': "an ONLINE event curated to celebrate the joy of writing. <br> Write to your heart’s content! <br> Participants present their long compositions, be it a story or a poem or a script. It’s free style so the composition doesn’t necessarily have to conform to any pre-existing literary structure, just words meaningfully strung together. <br> There will be a single round. Long compositions can be entered online. ",
        'rules': [
            "The entries will be checked for plagiarism against existing works and entries of other participants.", 
            "Original content is the only requirement. ",
            "No restriction on number of entries allowed per registration",
            "Event is open to all ",
            "Entries will not be categorically judged",
            "Upper word limit is 2000 words",
            "Entries must only be in ENGLISH"
        ],
        'regLink': "http://bit.ly/OdysseyContentWriting",
    },
]
dance = [{
        'id': 1,
        'img': '/eventImg/Battle Trouple-01.jpg',
        'name': "BattleTroupe'20",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Synchronised movements. Beating hearts. Screaming Spectators. <br> Feel their passion, feel their drive. Find yourself on your feet, rooting for your favourite team. <br> We present to you the most awaited event of the year that would let your minds and heart go crazy and the stage on fire. Dancer or not, the vibes would take you to places and send chills down through your spine as you sit and witness the best teams perform their hearts out. <br> The event would consist of 2 rounds. <br> Round 1: Video Round <br> Round 2: Finals <br> Video Preliminary Round- <br>  Length of the video should be 5-10 minutes <br> On stage limit is 5-17 members. Team limit is 40 members. <br> All dance forms, with the exception of Indian Classical, are permitted. <br> 10-12 teams shall be selected for finals. <br> Finals- <br> Length of performance should not exceed 7-10 minutes. <br> Teams will be given a stage setting time of 1.5 minutes (maximum). <br> All dance forms, with the exception of Indian Classical, are permitted. <br> On stage limit is 5-25 members. Team limit is 40 members.",
        'rules': [
            "Tracks for the teams must be carried in .mp3 format in a pendrive, hard drive or laptop as backup. Audio tracks have to be mailed a day before prelims and finals. ", 
            "No use of fire, smoke, or any substance that might damage the stage.",
            "Judge’s decision is final.",
            "For finals, teams would be required to report before the competition. Slotting would be done with society presidents. ",
            "All team members must carry their college id cards/ valid id proof."
        ],
        'regLink': "http://bit.ly/2M4L1nv",
    }, {
        'id': 2,
        'img': '/eventImg/streetdance_fbcover.jpg',
        'name': "Street Dance",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "8-30 (including all performers)",
        'description': "Unleash the spark in your movement and light up the streets! <br> Gather your team and make street dance a sensation in Delhi! <br> Submit your entries to get a chance to show off your street dancing skills in front of a large audience and potentially take home extravagant cash prizes!  <br> All teams would be required to submit video entries for the prelims. (Video Length: 3-5 minutes)  <br> Top 8-10 teams would be selected for the final (on-spot) round based on preliminary round, and get to perform at Odyssey ‘20. The winning team takes home grand cash prizes, along with a major sense of accomplishment and pride.",
        'rules': [
            "Team Size: 8-30 (including all performers)",
            "Styles: Hip-Hop, Popping, Tutting, Krumping, Breakdance, Stepping, Bboying, Contraptions and Western Freestyle. Deviation from hip-hop is discouraged.",
            "Judging Criteria: Choreograph, Energy, Synchronization, Stage utilization, Costumes, Innovation, Overall impact, Use of Retro Songs in the performance.",
            "Stage Specifications: Circular Stage with audience on all sides.",
            "Time limit: 6-8 min (+1 min setup time)",
            "Teams need to perform a dance sequence incorporating above mentioned dance styles without any theme.",
            "Judges have right to stop your performance in between.",
            "The decision of the judges will be final and binding.",
            "One person can be a member of only one team. ",
            "Heavy penalty shall be imposed on both teams if this is violated.",
            "Crews consisting of participants from mixed colleges are allowed but all members must be present college students (not necessarily from same college).",
            "Participants may use more than one song in their performance.",
            "Usage of props is allowed. These have to be brought by the teams themselves but the organizers hold the discretion of allowing it on stage.",
            "Pre-recorded music should be brought in a pen drive in .mp3 format only.",
            "Teams must follow the Time Limits and strictly stick to the allowed styles. Teams shall be penalized by organisers for not doing so.",
            "Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has possibility of tampering/damaging the stage is STRICTLY not allowed.",
            "Obscenity of any kind is not allowed and will lead to immediate disqualification.",
            "Violation of any of the above rules, will lead to heavy penalties"
        ],
        'regLink': "http://bit.ly/streetdanceodyssey",
    }, {
        'id': 3,
        'img': '/eventImg/Thematic cover.jpg',
        'name': "Thematic Group Dance",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "There are feelings, this heart can't convey. <br>There are messages, our words can't say.<br> And there are issues, we fail to put away.<br> So this time let those issues be dealt with dance. <br>Let your body speak what your words can't .<br>Dance is one of the most powerful tools to reach out to people.<br> It is a language which speaks to the heart.<br> With this notion at hand, we bring to you thematics- an event where a social concern is addressed with dance.<br>  There are no particular themes for this event.<br>Teams can perform on any theme they want.  <br>The dance style has to be western.",
        'regLink': "https://bit.ly/36JNdIL",
    }, {
        'id': 4,
        'img': '/eventImg/cyd_cover.jpg',
        'name': "Can you Duet",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "“Through synergy of intellect, artistry and grace came into existence the blessing of dancer.” So what are you waiting for? Come on and intensify this artistry together with a person having the same zest for dance. <br> Are you ready to be a part of one of the most popular dance events, an event where you can groove together with your partner? <br> Any two individuals can pair up (irrespective of their gender) to participate in this event. <br> Styles: Participants may perform any styles apart from Indian Classical and folk. <br> Judging Criteria: Synchronization, expressions, energy level, Stage utilization, Chemistry between the partners, and costumes. Innovativeness and creativity which appeals to the judges and the audience will be considered. <br> Stage Specifications:  Open stage  with audience on one side. <br> Slotting: The slotting procedure would be random. <br> Time Limit: 3-5 minutes.",
        'rules': [
            "Participants can be from different colleges, but both should be present college students.", 
            "One person can be in only one duo.",
            "Usage of props is allowed. These have to be brought by the teams themselves but the organizers hold the discretion of allowing it on stage.",
            "Pre-recorded music should be brought in a pen drive in .mp3 format only. Teams must follow the Time Limits and strictly stick to the allowed styles. Teams shall be penalized by organisers for not doing so.",
            "Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has the possibility of tampering/damaging the stage is STRICTLY not allowed.",
            "Vulgarity and obscenity at any point are strictly not allowed. It can lead to immediate disqualification. Songs should be chosen accordingly.",
            "Violation of any of the above rules will lead to heavy penalties.",
            "The decision of the judges shall be final and binding."
        ],
        'regLink': "https://forms.gle/nFL24HYFxSwCyUp66?fbclid=IwAR0PxWOJ24phjLC-_6eETzA9OZVEbEBrg32tyvD_v76ETQqaC9wexsxiy2E",
    }, {
        'id': 5,
        'img': '/eventImg/verve_cover.jpg',
        'name': "Verve",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Every participant would be required to submit a solo video entry for the preliminary round. (Video Length: 2-4 minutes)  <br> Top 20 participants would be selected for first round based on the online preliminary round, and get to perform at Odyssey ‘20. <br> Out of which, the judges select 9 participants for the battle round in which 3 battles will take place with 3 participants in each group. <br>The shortlisted participants will perform on given songs. <br> 1 participant from each group will be selected for the final battle round. <br> Eligibility Criteria: <br> Participants must be college or school students. <br> Age limit : 16-25 years",
        'rules': [
            "Western styles like Hip-Hop, Bboying, Jazz, Contemporary etc. ", 
            "Mixing of different styles is allowed. ",
            "Indian Classical and Folk is not allowed. ",
            "All participants must be present college or school students. ",
            "Time limit for the first round is 2-3 minutes (+1 min stage setup time) ",
            "There will be negative points for exceeding the time limit. ",
            "Usage of props is allowed. ",
            "They have to be brought by the participants themselves but the organisers hold the discretion of allowing it on stage. ",
            "Any kind of fluid, flame, powders, glitters, heavy or sharp objects or any material which has the possibility of tampering/damaging the stage is STRICTLY not allowed. ",
            "Obscenity of any kind is not allowed and will lead to immediate disqualification. ",
            "Violation of any of the above rules, will lead to heavy penalties. ",
            "The music should be mailed to (mail) by (date) in .mp3 format. ",
            "The music should also be brought in a pen drive in .mp3 format only and submitted at the time of registration."
        ],
        'regLink': "https://bit.ly/2tki2Wa",
    }, {
        'id': 6,
        'img': '/eventImg/mudra_cover.jpg',
        'name': "Mudra",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "Solo/Group",
        'description': "Classical Dance Event- The Indian classical solo/group dance competition at Odyssey’20.",
        'rules': [
            "Only Indian classical dance forms recognised by the Sangeet Natak Academy are allowed. ", 
            "Bharatnatyam",
            "Kathak",
            "Kathakali",
            "Kuchipudi",
            "Manipuri",
            "Mohiniyattam",
            "Odissi",
            "Sattriya",
            "The songs must be a professionally recorded classical music piece. It should not be a Bollywood movie song.",
            "Semi-classical music is allowed.",
            "Stage limit- Minimum: 1, Maximum: 12",
            "The time limit for the performance including stage set up",
            "Solo:5-10 minutes",
            "Duet: 5-10minutes",
            "Group:5-10 minutes",
            "The decisions of the judges are final and binding.",
            "Judgment criteria- Choreography and its execution,  Expressions, Costumes and Makeup, Technicalities."
        ],
        'regLink': "https://forms.gle/hcni9h477Lvq75KP8",
    }, 
]
fun = [{
        'id': 1,
        'img': '/eventImg/mtwi_psd.jpg',
        'name': "",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Your description para",
        'regLink': "https://www.facebook.com/events/432371520815294/ ",
    }, {
        'id': 2,
        'img': '/eventImg/huntit_fb_cover11.jpg',
        'name': "HuntIt",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Embark on an enthralling hunt which will test your wits with mind-bending clues. <br>Compete against teams from all over the city to be the first ones to get your hands on the treasure. <br>Be a part of the most exhilarating treasure hunt of the year and get a chance to prove your mettle and take home some sweet loot.",
        'regLink': "https://bit.ly/HuntIT20",
    }, {
        'id': 3,
        'img': '/eventImg/Blind date.jpg',
        'name': "Blind Date",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "A fun and exciting event where you get to spend time with someone you have never met, whom you don’t know. It’s fun to share interesting facts about yourself. With matches made on the basis of similar interests, you get to meet someone of 'your type', someone with whom you share your interests, ideas and perspectives. At the end of the day you have a great time with tons of memories and a fair possibility of making a new friend. <br> Event Structure: <br> You'll be blind folded for 2-3 minutes and allowed to interact with your partner. <br> There will be activities like pictionary to check your coordination and an in-campus selfie competition. <br> Rest all is a surprise!",
        'regLink': "http://bit.ly/blinddateodyssey",
    }, {
        'id': 4,
        'img': '/eventImg/Food Arena.jpg',
        'name': "Food Arena",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Food Arena, for all the foodies around the world, unleash your hunger, with the most exciting food from around the world.",
        'regLink': "http://bit.ly/foodarena20",
    }, {
        'id': 5,
        'img': '/eventImg/boc_cover.jpg',
        'name': "Battle of Chefs",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "4 to 5 Members",
        'description': "Stuff yourself with something unexpected, something that seems to be HELL but turns out to be HEAVEN. <br> Does your heart skip a beat every time someone talks about food ? <br> Are you Joey to your food ? <br> We believe there is no love greater than the love for food.<br> So we present to you a fun-filled cook-off challenge in one of the most awaited cultural fests of Delhi - Odyssey. This time , the teams will not only cook mouth-watering meals but also show their skill in selling what they create.<br> So get ready with your knives and food  <br> to set fire at IIITD! <br><br> We are planning to have two rounds. <br><br> In first round participants are open to make whatever they want from given ingredients in given time constraint . <br><br> For second round we will shortlist best 5 performers in the first round. Then we will give them some props that they have to use in their dishes and in second round we also going to judge them by the audience.",
        'regLink': "http://bit.ly/2PtgPo3",
    },
]
gaming = [{
        'id': 1,
        'img': '/eventImg/PUBG_FB.jpg',
        'name': "PUBG",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "Solo or Squad",
        'description': "PUBG Mobile tournament many teams which compete to get chicken dinner. <br> Each group is required to maintain four players in the team’s starting lineup. <br> Teams also have the option to add one more player who will act as a substitute. <br> There is no compulsion that the number of players in the team has to be five. <br> It’s the maximum number of players allowed in a group, and tournament officials reserve the right to disqualify teams if they are not meeting the required quorum of players. <br> A team should also have a captain assigned who will be the point of contact with the officials. <br> The captain needs to be part of the team roster for every game, and teams cannot change captains during the tournament.", 
        'rules': [
            "IN-GAME RULES", 
            "Players are expected to use their own devices in online events, but in LAN events, players are provided with dedicated tools meant only for playing in the tournament.",
            "Only smartphones are allowed to be used to play the game. ",
            "PCs, consoles, tablets, laptops or any other non-handheld device are not allowed. ",
            "Even using the official emulator on PC is not permitted.",
            "Players can only use devices running on Android or iOS.",
            "Maps that are used in games include Erangel, Miramar, Sanhok and Vikedi. ",
            "All games are played in Third Person Perspective (TPP). ",
            "There are no pauses permitted during the game for any reason other than some extreme cases like a natural calamity or a terrorist attack. ",
            "However, a game can be replayed if there are technical malfunctions or if a player disconnects (without their fault) within 90 seconds of the player landing on the battlefield, or if a problem occurs in the loading screen and the game doesn’t load, if the player is unable to move within 90 seconds and some other circumstances.",
            "Players will also have to take prior permission from the organisers if they plan to stream their gameplay.",
            "But there should be a five-minute delay in the stream.",
            "RULES FOR DISQUALIFICATION",
            "Official tournaments expect players to be professional at all times and observe the highest standards of personal integrity and sportsmanship. ",
            "However, if players are found to cooperate with other team members or members of other teams to provide any player with advantages or benefits, or pre-arranging to split the prize money or deliberately losing a tournament game for compensation will lead to disqualification of the team.",
            "Furthermore, cheating of any sort is prohibited. ",
            "Fraud includes use of any cheating device or program, or any other method like signalling devices, hand signals, talcum power or screen protectors.",
            "Intentionally using any in-game bug to get an undue advantage is also prohibited. ",
            "Players also cannot use another player’s account to play. ",
            "Moreover, vulgar or hateful speech, violence, drugs and alcohol, gambling, studio interference and unauthorised communication will lead to disqualification.",
            "Apart from disqualifications, authorities also have the right to impose penalties which include verbal or written public warnings, forfeiture and bans."
        ],
        'regLink': "http://bit.ly/2RZHZoj",
    }, {
        'id': 2,
        'img': '/eventImg/pwnedFBCOVER.jpg',
        'name': "PWNED",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'description': "This is *the*  event to test your gaming skills. <br>Come show off your how well your hands know their way on that controller and thrash your opponent like a psychopath. <br>You'll have a plethora of options when it comes to asserting dominance over your opponent, you can shoot some stunning goals on FIFA, bring your opponent to a gore-filled bloody ending in Mortal Kombat, show your godly skills in Injustice or stupefy the crowd and be the last man standing in Royal Rumble.",
        'rules': [
            "The event is a competitive knockout based tournament where you must slay down your opponent to thrive. ", 
            "You'll have two chances to prove your worth!"
        ],
        'regLink': "http://bit.ly/2PMQGQ5",
    }, 
]
arts = [{
        'id': 1,
        'img': '/eventImg/graffiti_cover.jpg',
        'name': "Grafitti",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "We are all artists, painting our lives upon the canvas of reality.<br> With Graffiti, why not paint our canvas of imagination too?<br> This event aims to provide a platform to the participants to showcase their creativity through wall art.",
        'rules': [
            "Registrations will be done online.", 
            "The concept will be provided by the organiser. The themes for the prelims will be declared in advance; those for the finals will be declared on the day of fest itself.",
            "Teams of 3 to 5 people are eligible for participation.",
            "Canvas/wall will be provided along with spray cans.",
            "Any other material you wish to use should be arranged yourself.",
            "All participants must complete their murals within four hours.",
            "Artwork must be completed on the canvas provided.",
            "Participants should adhere to the instructions and refrain from copying ideas.",
            "The artworks will be evaluated by the judges chosen by the organisers. The criteria for judging include Lettering, Concept, Colour, Originality and Technique. The decision of the judges will be final."
        ],
        'regLink': "https://bit.ly/2PlBzOo",
    }, {
        'id': 2,
        'img': '/eventImg/fine arts2.jpg',
        'name': "Fine Arts",
        'date': "TBA",
        'time': "11:00 am - 5:00 pm",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-3 members per team",
        'description': "Fun art events lighten the mood of the fest and encourage students to go back to creating clutter and presenting their wide world of ideas. <br>It’s time to wake up the painter inside you with fine arts at odyssey’20.",
        'rules': [
            "Open to all age groups", 
            "Participants to bring their own medium of painting (Charcoal, water colors, poster colors, pencil sketching, oil pastels etc). All types of mediums are allowed. Any of A3, A2, A1 white sheets will be provided as per the participant's requirement.",
            "Any technique of painting can be used.",
            "The teams will have to choose a theme from the provided set of themes.",
            "Candidates will be provided with their sheets of choice A1/A2/A3 and given themes on the spot (they can choose from the themes given on the spot). ",
            "Maximum of 3 hours will be given to present your work. ",
            "After this there will be a short break during which judges would decide the best 3 art works. ",
            "Announcement of results and prize distribution will take place on the same day."
        ],
        'regLink': "http://bit.ly/FineArts-20",
    }, {
        'id': 3,
        'img': '/eventImg/face painting.jpg',
        'name': "Face Painting",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "“Aao ye chehra rang de <br> Jo khayalat hain unko bunn de <br> Ye jo tajassus ki kashti hai usko kinara de den”<br>Face painting event is a one-day event (approximately 3 hours long) on the second day of Odyssey.",
        'rules': [
            "The participants are required to bring their own paints and brushes", 
            "Only the first few (10-15) teams would be provided with paints.",
            "The theme would be provided to the participants one day before the event.",
            "The event would be open theme synonymous with the theme of ODYSSEY’19",
            "Teams of at max 3 members (including the person on whom painting will be done)",
            "Entries will be judged by judges/OT just after the event. In all cases the judge’s decision is final."
        ],
        'regLink': "http://bit.ly/35xdR7q",
    }, 
]
photography = [{
        'id': 1,
        'img': '/eventImg/Captcha_FB.jpg',
        'name': "Captcha",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "In photography there is a reality so subtle that it becomes more real than reality.” <br> We humbly invite all the enthusiasts to come join us .<br>There will be an online preliminary round close to the date of the event, followed by an on-campus photography round. <br> Event Structure- <br> 1. There will be an online preliminary round for all the events. <br> 2. It will be a two-day event with Mobile photography and DSLR photography on Day 1 and Chitra on the second day <br> 3. Two stage elimination",
        'rules': [
            "Stay tuned for the additional details.", 
            "Follow us on our social media handles to stay updated."
        ],
        'regLink': "https://bit.ly/2EqxJNG",
    }, {
        'id': 2,
        'img': '/eventImg/oec_fb.jpg',
        'name': "Online Editing",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Online Editing Challenge is a photo-editing challenge designed for both beginners and experienced people. Participants would be given photos to edit and would be using techniques like layered photography. There is no age limit. <br> Everything is up to you guys. Feel free to edit the photo any way you want. Be as creative or be as realistic as you want to make things amazing. <br> Software’s you can use to edit your photo will be: - <br> 1. Adobe Lightroom CC <br> 2. PicsArt <br> 3. Snapseed <br> 4. Or any other ",
        'rules': [
            "You can edit the given photo on laptop or mobile phone.", 
            "You have to mention the software you are using",
            "You will have to upload the photo edited in the same resolution, cropping the photo is not allowed.",
            "You are allowed to remove very small portions of photo by patch tool in Adobe Photoshop."
        ],
        'regLink': "https://bit.ly/36A4gga",
    }, 
]
lifestyle = [{
        'id': 1,
        'img': '/eventImg/reverbe.jpg',
        'name': "Reverbe",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "Permitted team size is 15-22. At max 4 designers and 14 models along with maximum 4",
        'description': "To all the cinderellas and prince charmings, pick out your fanciest outfits, dazzeling- most jewellery items, highest heels and thickest capes. <br> ‘Lo and Behold because the most awaited fashion event of the year is back with a bang. <br> Introducing REVERBE 2020! <br> Save the dates , write them on sticky notes and paste them onto your mirror because you gotta strut and Sizzle on the Odyssey stage on the third weekend of January. <br> It takes more than a pretty face or figure to be a model , more than a good artist to be a designer and more than friendship to be a Competitive team in one of India’s biggest and most glamorous lifestyle events. <br> Do you think your Fashion Team is capable enough? Participate NOW to find out!",
        'rules': [
            "You can choose your own theme.", 
            "Participating teams should carry their music on a CD or Aux.",
            "Teams must be well versed with their light requirements so as to be able to utilise their transition time period optimally.",
            "­Vulgarity is strongly prohibited. Any form of obscenity will lead to debarring the team from the competition.",
            "­Use of cigarettes, alcohol, and any unfair means is strongly prohibited.",
            "Duration of performance : ­Time limit (per team-from when your team is announced to when you get off the ramp) : 10 minutes(on stage time) + 5 minutes for choreo adjustments and transition time."
        ],
        'regLink': "http://bit.ly/4RSILSS",
    }, {
        'id': 2,
        'img': '/eventImg/Trashion-01-01.jpg',
        'name': "Trashion",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "A fashion event in which outfits are designed from used/thrown out and repurposed elements. <br><br> EVENT STRUCTURE: <br> For the event we will be conducting two rounds, the key points are: <br> Round1: <br> ·        Any theme can be chosen by the participants. <br> ·        Since there will be a large number of people participating in round1 so we will provide them with limited but sufficient resources. <br> ·        Time based (1 hour 30 minutes, approx.) <br> ·        Ramp walk (preferably on stage-depends on its availability) <br> ·        Since the number of participants will be large in this round, they may start their work anywhere nearby venue. <br> ·        Participants will get only one chance for the ramp walk. <br> Round2: <br> ·        The theme for the final round will be vintage. <br> ·        Participants will have access to all the resources available (much more than sufficient) . <br>  ·        Time based (2 hours, approx.) <br> ·        Ramp walk (on stage) <br> ·        Participants will strictly be placed in a room or so. <br> ·        All the participating teams might practice once on the stage (while we will collect the audiences for our event). After that, only the final walk will be allowed.",
        'rules': [
            "A team can have at most 5 members and a minimum of 2.", 
            "Plagiarism Policy, if any team found copying the idea then that team will be disqualified, ideas should be unique.",
            "Vulgarity is strictly prohibited, any scene of obscenity will lead to immediate disqualification."
        ],
        'regLink': "https://bit.ly/34tpwTA",
    }, 
]
music = [{
        'id': 1,
        'img': '/eventImg/schism.jpg',
        'name': "Schism",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "Make Music not War... unless its the BATTLE OF BANDS <br> Schism is a nation-wide Battle of the Bands event being held during IIITD’s cultural fest Odyssey.<br> Watch as the best bands from all over India go head to head on stage to see who can make the crowd jump the highest, sing along the loudest and headbang the hardest. <br>Come, feel the energy of earth-shaking riffs and face-melting solos and find out for yourselves which region of India rocks the hardest.",
        'rules': [
            "All bands must register on the registration form given on the Facebook page or website to be eligible for participation.", 
            "In the first round (online), all participating bands are expected to submit a video of their performance of a song - either a cover of an existing song or an original song (no constraint in this round). The submission should be of 2-3 minutes.",
            "In the second round (live), selected bands will be expected to perform at least one original composition. The group will get 25 minutes inclusive of setup and teardown(the setting up includes soundcheck for microphones too, the first sound heard on the speakers).",
            "There will be severe repercussions if the time limit is not followed. After 25 minutes, there would be a deduction in points. At 28th-minute, complete system sound cut, and at the 30th minute, the team would be disqualified.",
            "The number of members per team must be 3-15.",
            "No participant should be greater than 25 years of age.",
            "Each team must have a dress color, which should be informed to the organizers beforehand. ",
            "The decision of the organizing team and the judges will be final.",
            "Any undignified act which may bring embarrassment to the students, management, or the college will be dealt with seriously."
        ],
        'regLink': "http://bit.ly/SCHISM20",
    }, {
        'id': 2,
        'img': '/eventImg/acapellujahfbcover.jpg',
        'name': "Acapellujah",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "We at IIIT Delhi are super excited to announce return of a fresh season of Acapellujah:- The acapella competition in our much awaited cultural fest Odyssey! <br>Does your team have what it takes to create mind blowing music using simply vocals and no instruments whatsoever?<br> If yes, then our event is the perfect place for you and your team to showcase your talents! <br>Come join us for a day filled with tuneful melodies, foot tapping beats and harmonies that are sure to take your breath away!", 
        'rules': [
            "1. More than 1 team from each college/institution is allowed to register and take part in the event.", 
            "2. Each team’s piece is required to be original.",
            "3. Duration of the performance would be 13 minutes at maximum, including the time taken to set up the performance and conduct audio checks etc.",
            "4. The piece can be of any genre/language. Get creative with it ☺",
            "5. Only one round will be conducted.",
            "6. Registered teams are required to send in an email to (insert corresponding email address) containing the number of microphones (or other audio equipment that can be provided and accommodated by IIITD) they would require for their performance.",
            "7. The minimum number of participants are 3 and the maximum number of participants are 25.(conductor included)",
            "8. The description of their piece and the idea behind it must be explained within the time frame given (12 minutes)",
            "9. Judge decision will be final and binding."
        ],
        'regLink': "bit.ly/acapellujah",
    }, {
        'id': 3,
        'img': '/eventImg/EncoreWestern-01.jpg',
        'name': "EncoreWestern",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1 Member",
        'description': "Music is a language that doesn't speak in particular words. It speaks in emotions, and if it's in the bones , it's in the bones. - - Keith Richards <br> Odyssey 2020 is back with encore(western)!. Here is your chance to enthrall the audience with your passion and love for music. <br> Showcase your talent and win exciting prizes. <br> WHAT : Western solo singing competition <br> Registrations(offline) : 18 Jan , 8.00AM - 10.00AM",
        'rules': [
            "1. Team size : Solo", 
            "2. Teams per college/school : Unlimited",
            "3. Age: 16 to 24",
            "4. There will be 2 rounds : Prelims and Final. ",
            "Prelims will be online while the Final round will be at our college.",
            "5. Songs must be in English.",
            "6. The decision of the judges shall be final and binding .",
            "7. Obscenity(at the discretion of judges) of any kind is not allowed and will lead to immediate disqualification.",
            "8. The time limit is 3 - 4 minutes and should be strictly followed.",
            "9. The decision of the organizers  regarding the final line-up would be considered absolute."
        ],
        'regLink': "https://forms.gle/AgCZ8ri1L6pd4jNUA",
    }, {
        'id': 4,
        'img': '/eventImg/EncoreIndian-01-01.jpg',
        'name': "EncoreIndian",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "TBA",
        'description': "“Without ambition, one starts nothing. Without work, one finishes nothing. <br>The prize will not be sent to you. <br>You have to win it.” Your vocals are the face of your talent. Participants trained in the vocal aspects of Indian style are invited to compete. <br>Showcase your talent and win exciting prizes. <br> Online Portal Round <br> ● Submit a 2-3 min piece of music on the online portal we’ll share. <br> ● Background music permitted. <br> ● The submitted piece should have clear voice, and the participant shouldn’t autotune the piece or record it in someone else’s voice. This would lead to immediate disqualification. <br> Judging Criteria: <br> ● Preparedness <br>● Fundamentals (Pitch, Tone, Rhythm, tempo) <br> ● Voice quality (tonality, appropriateness to the genre, &amp; technique, breath control) <br> The participants chosen in this round would be permitted to present their talent in the next upcoming rounds at IIITD Campus.<br> Prabhav (Finale) <br>Choose a song of any genre. Incorporate some changes to make the song your own, at the same time preserve the original beauty of the song. <br> Single hand instrument or background karaoke music is allowed. (Karaoke file should be shared with us via email, 1 day prior to the day of the event)",
        'rules': [
            "➔ Team Size: 1",
            "➔ Age group: 16-22",
            "➔ Teams per college/school: Unlimited",
            "➔ Rounds: Online Round, Prabhav, Apnapan",
            "➔ Songs must be in Hindi.",
            "➔ Rap portions or refrains are not permissible.",
            "➔ The decision of the judges shall be final and binding",
            "➔ Obscenity (at the discretion of judges) of any kind is not allowed and will lead to immediate disqualification.",
            "➔ The time limit should be strictly followed.",
            "➔ The decision of the organizers regarding the final line-up would be considered absolute.",
            "➔ All rounds, except the online round, will take place in IIIT Delhi campus."
        ],
        'regLink': "https://docs.google.com/forms/d/e/1FAIpQLSc8zYUYBptfBJ05--1kobub5OxQHVnf_gHaNyna5lt_axnhpg/viewform?usp=sf_link",
    }, {
        'id': 5,
        'img': '/eventImg/war of djs.jpg',
        'name': "War Of DJs",
        'date': "TBA",
        'time': "TBA",
        'venue': "TBA",
        'prize': "TBA",
        'team': "1-2 Members",
        'description': "Do you think you possess the ability to spin and move the crowd with your beats? Do you think you can fuel the crowd by the fire of your music from mixers and turntables? <br> Odyssey’20 welcomes you to showcase your passion of DJing with it’s event  <br> “War of DJs” - the war of rhythm and beats. A head to head battle between DJs with their compositions. <br> So get into the groove and come spin with us! <br> Round 1: Participants will be given a midi file on the day of the event. Then they'll use their DAWs like logic, FL studio, Ableton etc. to make music. This will be played one by one in front of the judges and then 5 to 8 people will proceed to the next round. <br> Round 2: In this round the selected people will give a DJ performance in front of a live audience.",
        'rules': [
            "Round 1: There must be no copying of track covers.", 
            "Round 2: During mixing there should be no cursing on the mic. Use of sync button will not be allowed and if used, it would lead to penalty.",
            "Age limit: There is no age bar. People of all ages can participate.",
            "Equipment: Required hardware would be provided on the day but it would be preferable if participants bring their own equipment. ",
            "Time limit: Time limit to make music for round 1 will be 2.5-3 hours and time limit for the second round performance would be 10-15 minutes.",
            "Team size : Solo / Duo"
        ],
        'regLink': "https://forms.gle/kJfc53frWgw4bHYt7",
    }, 
]
eventsData = {
    "theater": theater,
    "dance": dance,
    "fun": fun,
    "photography": photography,
    "arts": arts,
    "gaming": gaming,
    "lifestyle": lifestyle,
    "literary": literary,
    "music": music
}